gitcoinco/easy-retro-pgf

- funding.json
> add funding.json

- .env.example
- README.md
- docker-compose.yml
part of #56 
* add a docker-compose file to run a local postgres instance
* update default env vars to use it
* update docs in README
> local postgres instance config

- src/features/admin/layouts/AdminLayout.tsx
- src/features/rounds/types/index.ts
- src/pages/[domain]/admin/index.tsx
> Fix #59 Select Round type

- src/features/ballot/hooks/useBallot.ts
- src/features/metrics/components/AddToBallotButton.tsx
- src/features/metrics/components/MetricDetails.tsx
- src/features/metrics/components/MetricsList.tsx
- src/pages/[domain]/metrics/[metricId]/index.tsx
- src/server/api/routers/ballot.ts
- src/server/api/routers/metrics.ts
- src/server/api/trpc.ts
- src/utils/fetchMetrics.ts
> Ballot metric allocations

- prisma/schema.prisma
- src/features/ballotV2/hooks/useBallot.ts
- src/features/metrics/components/AddToBallotButton.tsx
- src/pages/[domain]/ballot/metrics.tsx
- src/server/api/root.ts
- src/server/api/routers/ballotV2.ts
- src/server/api/trpc.ts
- #64 
Created a BallotV2 model. Later we can refactor the Projects ballot to use this one.
---
> Impact Metrics Ballot

- src/features/projects/components/Projects.tsx
- src/features/projects/components/ProjectsResults.tsx
- src/features/rounds/hooks/useIsShowActualVotes.ts
- src/features/stats/utils/generateResultsChartData.ts
- src/hooks/useResults.ts
- src/pages/[domain]/stats/index.tsx
- src/server/api/routers/results.ts
- src/utils/calculateResults.test.ts
- src/utils/calculateResults.ts
- src/utils/filterKnownNullBallots.ts
- **`src/features/projects/components/Projects.tsx`**
- Updated the `Projects` component to conditionally display `actualVotes` or `votes`.
- **`src/features/projects/components/ProjectsResults.tsx`**
- Updated the `ProjectsResults` component to conditionally display `actualVotes` or `votes`.
- **`src/features/rounds/hooks/useIsShowActualVotes.ts`** (new file)
- Added a hook to check if the current domain should show actual votes.
- **`src/features/stats/utils/generateResultsChartData.ts`** (new file)
- Added a utility function to generate chart data for project results.
- This function generates both `calculatedData` and `actualData`.
- **`src/hooks/useResults.ts`**
- Updated `useProjectResults` to conditionally show `actualVotes` or `votes`.
- Added `useAllProjectsResults` hook to fetch …
> feat(RED-51): add functionality to conditionally show actual result votes

- .gitignore
- src/features/admin/components/AddAddresses.tsx
- src/pages/[domain]/admin/voters/index.tsx
- src/server/api/routers/voters.ts
Fixes: PAR-235
Track which voters have voted in admin
> feat: track which voters have voted in admin

- src/features/distribute/hooks/useAlloPool.ts
> fix pool error

- src/features/applications/types/index.ts
> feat: update schema for onChainSummer metadata

- src/features/metrics/components/BallotSidebar.tsx
- src/features/metrics/components/MetricsList.tsx
- src/features/metrics/components/MetricsSidebar.tsx
> show ballot only to valid voter

- src/features/distribute/components/Distributions.tsx
- src/features/distribute/components/ExportCSV.tsx
- src/features/distribute/components/ImportCSV.tsx
- src/features/distribute/types/index.ts
- src/utils/awards.ts
> import-export-csv

- src/features/ballot/components/SubmitBallotButton.tsx
https://linear.app/gitcoin/issue/PAR-291/view-ballot-button-should-link-to-the-correct-ballot-page
> Fix #291 Correct View Ballot link

- src/server/api/routers/voters.ts
Currently we use ballotV2. signature to see if a person has voted but this is not right the UI doesn't ask for a signature if the user has already signed for a previous round. This causes confusion where if you have voted on round 1 , it shows up as you've voted in any other round.
This updates the check to rely on allocations table which is accurate and filter by round
http://localhost:3000/test-round/admin/voters
> fix hasVoted query

- src/features/projects/components/ProjectDetails/AddressBox.tsx
- src/utils/copyToClipboard.ts
> feat: copy to clipboard for AddressBox

- src/server/api/trpc.ts
> API key same request

- src/components/ui/Button.tsx
- src/features/applications/components/ApplicationItem.tsx
- src/features/applications/components/ApplicationReviewActions/ReviewActionButton.tsx
- src/features/applications/components/ApplicationReviewActions/index.tsx
- src/features/applications/hooks/useApplicationReview.ts
- src/server/api/routers/applications/applicationsRouter.ts
- src/server/api/routers/applications/utils/fetchApprovals.ts
- src/server/api/routers/applications/utils/getApplicationStatus.ts
> fix: applicationItem status

- src/components/Header.tsx
- src/components/ui/Alert.tsx
- src/features/ballot/components/SubmitBallotButton.tsx
- src/layouts/DefaultLayout.tsx
- src/layouts/MetricsLayout.tsx
- src/server/api/routers/ballot.ts
- fix view ballot link
- rename Metrics -> Voting
- Add distribute navLink in the header
- Download Votes button has mismatch data
- More meaningful msg when user is not connected
closes PAR-338
closes PAR-337
closes PAR-342
closes PAR-344
closes PAR-339
> sunny awards fixes

- src/components/EnsureCorrectSession.tsx
- src/providers/index.tsx
this fixes our issue when a user connects to another account and refreshes the page and having a mismatch between the wagmi address and the session address
fixes PAR-260
> feat: EnsureCorrectSession wrapper

- src/server/api/routers/applications/applicationsRouter.ts
- src/server/api/routers/applications/utils/fetchApplications.ts
> fix: filtering bug

- src/server/api/routers/projects.ts
returning Cursor for the onchain summer leaderboard
> chore:  Adding nextPage cursor to response

- src/features/ballot/components/BallotEditor.tsx
- src/features/ballot/components/ImportCSV copy.tsx
- src/features/ballot/components/ImportCSV.tsx
- src/utils/csv.ts
> fix: import votes

- prisma/schema.prisma
- src/components/AllocationInput.tsx
- src/features/admin/components/ImportVotersCSV.tsx
- src/features/ballot/components/BallotOverview.tsx
- src/features/voters/hooks/useImportVoters.ts
- src/features/voters/hooks/useVotesCount.ts
- src/pages/[domain]/admin/voters/index.tsx
- src/server/api/routers/ballot.ts
- src/server/api/routers/voters.ts
- src/server/api/trpc.ts
- src/utils/csv.ts
- src/utils/fetchVoterLimits.ts
> Add support for Custom Ballot size per Badgeholder

- src/features/ballot/components/SubmitBallotButton.tsx
> chore: refetch after ballot submission

- src/features/applications/components/ApplicationsList.tsx
- src/features/applications/hooks/useApplications.ts
- src/server/api/routers/applications/applicationsRouter.ts
- src/server/api/routers/applications/utils/fetchApplications.ts
The page selector was showing always the amount of pages for the tab 'All'
Added Rejected tab
- refactor api.applications.list to return the count of applications per status
- refactor ApplicationsList to display the right amount of pages per status
> fix: pagination page selector

- public/possibleSpamIds.ts
- src/features/applications/components/ApplicationsList.tsx
- src/features/applications/hooks/useApplications.ts
- src/server/api/routers/applications/applicationsRouter.ts
- src/server/api/routers/applications/utils/fetchApplications.ts
- added a new tab "Spam?" in applications review page
- created a file  public/possibleSpamIds.ts with an array to be populated with possible spam ids
> feat: added functionality to ignore possible spam application ids

- src/server/api/routers/projects.ts
> chore: filter spams from approvedIds + removed mock metric ids

- src/roundIDs.ts
- src/server/api/routers/applications/utils/fetchApprovedApplications.ts
- src/server/api/routers/projects.ts
- src/utils/fetchAttestations/types.ts
> chore: the sunnys hardcoded approvals

- src/server/api/routers/rounds.ts
> feat: my rounds include all rounds user is admin
